""" 
Revision ID: 487063d1f32f
Revises: 
Create Date: 2025-07-28 14:34:59.786809
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487063d1f32f'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('channels',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('invite_link', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_channels_owner_id'), 'channels', ['owner_id'], unique=False)
    op.create_table('support_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lotteries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prize', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('media_file_id', sa.String(), nullable=True),
    sa.Column('participation_button_text', sa.String(), nullable=True),
    sa.Column('winners_count', sa.Integer(), nullable=False),
    sa.Column('publication_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_condition_type', sa.String(length=20), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_participants_count', sa.Integer(), nullable=True),
    sa.Column('has_captcha', sa.Boolean(), nullable=False),
    sa.Column('captcha_type', sa.String(), nullable=True),
    sa.Column('boost_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotteries_channel_id'), 'lotteries', ['channel_id'], unique=False)
    op.create_index(op.f('ix_lotteries_creator_id'), 'lotteries', ['creator_id'], unique=False)
    op.create_index(op.f('ix_lotteries_end_time'), 'lotteries', ['end_time'], unique=False)
    op.create_index(op.f('ix_lotteries_publication_time'), 'lotteries', ['publication_time'], unique=False)
    op.create_index(op.f('ix_lotteries_status'), 'lotteries', ['status'], unique=False)
    op.create_table('giveaway_channels',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('giveaway_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['giveaway_id'], ['lotteries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('giveaway_id', 'channel_id', name='uq_giveaway_channel')
    )
    op.create_index(op.f('ix_giveaway_channels_channel_id'), 'giveaway_channels', ['channel_id'], unique=False)
    op.create_index(op.f('ix_giveaway_channels_giveaway_id'), 'giveaway_channels', ['giveaway_id'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('giveaway_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('captcha_passed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['giveaway_id'], ['lotteries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('giveaway_id', 'telegram_user_id', name='uq_participant_giveaway_user')
    )
    op.create_index(op.f('ix_participants_giveaway_id'), 'participants', ['giveaway_id'], unique=False)
    op.create_index(op.f('ix_participants_telegram_user_id'), 'participants', ['telegram_user_id'], unique=False)
    op.create_index(op.f('ix_participants_user_id'), 'participants', ['user_id'], unique=False)
    op.create_table('winners',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lottery_id', sa.BigInteger(), nullable=False),
    sa.Column('participant_id', sa.BigInteger(), nullable=False),
    sa.Column('place', sa.Integer(), nullable=False),
    sa.Column('is_additional', sa.Boolean(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lottery_id'], ['lotteries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lottery_id', 'participant_id', name='uq_winner_lottery_participant'),
    sa.UniqueConstraint('lottery_id', 'place', name='uq_winner_lottery_place')
    )
    op.create_index(op.f('ix_winners_lottery_id'), 'winners', ['lottery_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_winners_lottery_id'), table_name='winners')
    op.drop_table('winners')
    op.drop_index(op.f('ix_participants_user_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_telegram_user_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_giveaway_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_giveaway_channels_giveaway_id'), table_name='giveaway_channels')
    op.drop_index(op.f('ix_giveaway_channels_channel_id'), table_name='giveaway_channels')
    op.drop_table('giveaway_channels')
    op.drop_index(op.f('ix_lotteries_status'), table_name='lotteries')
    op.drop_index(op.f('ix_lotteries_publication_time'), table_name='lotteries')
    op.drop_index(op.f('ix_lotteries_end_time'), table_name='lotteries')
    op.drop_index(op.f('ix_lotteries_creator_id'), table_name='lotteries')
    op.drop_index(op.f('ix_lotteries_channel_id'), table_name='lotteries')
    op.drop_table('lotteries')
    op.drop_table('support_requests')
    op.drop_index(op.f('ix_channels_owner_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ### 