""" 
Revision ID: 82edc6534569
Revises: 487063d1f32f
Create Date: 2025-08-01 12:41:13.024657
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82edc6534569'
down_revision = '487063d1f32f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lotteries', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_column('lotteries', 'title')
    op.drop_column('lotteries', 'captcha_type')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotteries', sa.Column('captcha_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('lotteries', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('lotteries', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ### 